### ISSUE TITLE
Having trouble to build single pages for the items on my AlphabetS collage.

### ISSUE THREAD

**Issue by koidioble** [koidioble/www.blefacts.github.io#1]
Hi, I'm new on flutter. I'm working on app that I want to publish and it will my first as beginner. I built an AlphabetScrollPage in a Scaffold with 56 items in it. My goal is to have a single pages describing all item individually. Like when to click on one it automatically directly you to a new page.
I'm actually having a snackBar when you click on one it's comes with a Text saying you 'clicked on this $item'. Any help will be beneficial, thank you!
![Screen Shot 2021-09-25 at 8 35 38 PM](https://user-images.githubusercontent.com/64460870/134789268-7f8c05dc-0821-4e31-aa66-c54eb4286617.png)

**Comment by koidioble** [comment]
> Hi, I'm new on flutter. I'm working on app that I want to publish and it will my first as beginner. I built an AlphabetScrollPage in a Scaffold with 56 items in it. My goal is to have a single pages describing all item individually. Like when to click on one it automatically directly you to a new page.
> 
> I'm actually having a snackBar when you click on one it's comes with a Text saying you 'clicked on this $item'. Any help will be beneficial, thank you!
> 
> ![Screen Shot 2021-09-25 at 8 35 38 PM](https://user-images.githubusercontent.com/64460870/134789268-7f8c05dc-0821-4e31-aa66-c54eb4286617.png)
> 
> 
> 
>

**Comment by warpaltarpers** [comment]
Hi there, I'd love to help you with your issue! Is this part of another GitHub repository that I would be able to fork & clone so that I can take a look and see what can be done? I can't seem to find the files in your above screenshot in this repository.

**Comment by koidioble** [comment]
Hello, Thank you already for reaching. I would give you the exact code describing the situation. The first one is the AZItem with the code and the second one (page 16 - 18 of the pdf) describing the result. I hope it would help
[import 'package:azlistview:azlistview.dart';.pdf](https://github.com/koidioble/www.blefacts.github.io/files/7274601/import.package.azlistview.azlistview.dart.pdf)

[import 'package:ble:pages:alphabet_scroll_page.dart';.pdf](https://github.com/koidioble/www.blefacts.github.io/files/7274616/import.package.ble.pages.alphabet_scroll_page.dart.pdf)
